title: Latin dictionaries
author: Nikita Murzintcev
repository: latin-dict/latin-dict.github.io
url: https://latin-dict.github.io
baseurl: 
google_analytics: UA-140847555-1

collections:
  dictionaries:
    output: true
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "dictionaries"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
